# Site wide configuration

title: Data Analytics 
locale: en_US
logo: ![Profile](https://morwarid1.github.io/images/Profile.png)

# <img src="https://morwarid1.github.io/images/Profile.png" width="200"> 



# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Morwarid Najafizada
  avatar: Profile.png
  bio: "lets learn together"
  email: morwarid.najafizada@gmail.com
  # Do not include the @ symbol in your Twitter username
  twitter: #morwarid2
  linkedin: Morwarid
  github: morwarid1
  tableau: morwarid.najafizada
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
  facebook: #username
  instagram: morwarid_in_data 
  bing-verify:
  stackoverflow: #123456/username from a "https://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#CC0000'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
#creative-commons:
  #cc-by: #yes
  #cc-by-nc: yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
